//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVSwitcher.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IVSwitcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   All settings are done!
        ///If you added a shortcut, you can launch from the shortcut!
        ///If you have entered a Steam URL, do not delete the original shortcut.
        ///You can close the software if you want. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CFG_Configuration {
            get {
                return ResourceManager.GetString("CFG_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   The following files are not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string main_json_not_found {
            get {
                return ResourceManager.GetString("main_json_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading mod version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string main_mod_loading {
            get {
                return ResourceManager.GetString("main_mod_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading online version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string main_online_loading {
            get {
                return ResourceManager.GetString("main_online_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete selected items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string settings_dll_del {
            get {
                return ResourceManager.GetString("settings_dll_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the files you want to disable except for the ASI loader. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string settings_dll_listbox {
            get {
                return ResourceManager.GetString("settings_dll_listbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string settings_dll_select_btn {
            get {
                return ResourceManager.GetString("settings_dll_select_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following files are not recommended to be added
        ///Do you still want to add them? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string settings_dll_warn {
            get {
                return ResourceManager.GetString("settings_dll_warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GTA5exe has been found! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string settings_gtav_exists {
            get {
                return ResourceManager.GetString("settings_gtav_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GTA5.exe is not found! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string settings_gtav_no_exists {
            get {
                return ResourceManager.GetString("settings_gtav_no_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GTAV installation destination is not specified or GTAV.exe is not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string settings_gtav_not_found_message {
            get {
                return ResourceManager.GetString("settings_gtav_not_found_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GTAV installation folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string settings_location {
            get {
                return ResourceManager.GetString("settings_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string settings_location_open {
            get {
                return ResourceManager.GetString("settings_location_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location of the installation folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string settings_location_text {
            get {
                return ResourceManager.GetString("settings_location_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OSS License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string settings_oss {
            get {
                return ResourceManager.GetString("settings_oss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * MaterialDesignInXamlToolkit
        ///
        ///The MIT License (MIT)
        ///
        ///Copyright (c) James Willock,  Mulholland Software and Contributors
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///fur [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string settings_OSS_LICENCE {
            get {
                return ResourceManager.GetString("settings_OSS_LICENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add a shortcut to the desktop from the launcher, copy its url and paste it here に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string start_up_cfg_kam {
            get {
                return ResourceManager.GetString("start_up_cfg_kam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click on the button below to open the instructional video and follow the instructions. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string start_up_cfg_pad {
            get {
                return ResourceManager.GetString("start_up_cfg_pad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add a shortcut to the desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string startup_cfg_add_sc {
            get {
                return ResourceManager.GetString("startup_cfg_add_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start by specifying the exe file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string startup_cfg_call_exe {
            get {
                return ResourceManager.GetString("startup_cfg_call_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start by specifying the URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string startup_cfg_call_url {
            get {
                return ResourceManager.GetString("startup_cfg_call_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make the icon a GTAV one. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string startup_cfg_desktop_icon_gta {
            get {
                return ResourceManager.GetString("startup_cfg_desktop_icon_gta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon by https://icons8.com に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string startup_cfg_icon {
            get {
                return ResourceManager.GetString("startup_cfg_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icons provided に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string startup_cfg_icon_menu {
            get {
                return ResourceManager.GetString("startup_cfg_icon_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   by IV Switcher に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string startup_cfg_SC_comment {
            get {
                return ResourceManager.GetString("startup_cfg_SC_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start with GTAV MOD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string startup_cfg_SC_name_mod {
            get {
                return ResourceManager.GetString("startup_cfg_SC_name_mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launch with GTAV ONLINE version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string startup_cfg_SC_name_online {
            get {
                return ResourceManager.GetString("startup_cfg_SC_name_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How to start GTAV に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string startup_cfg_select_type {
            get {
                return ResourceManager.GetString("startup_cfg_select_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal Startup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string startup_cfg_select_type_kam {
            get {
                return ResourceManager.GetString("startup_cfg_select_type_kam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launch via Steam (optimal for the controller. Steam must be installed) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string startup_cfg_select_type_pad {
            get {
                return ResourceManager.GetString("startup_cfg_select_type_pad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This feature is under development. If you want to use a controller, please add EpicGamesLauncher or similar to Steam and enter it. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string startup_cfg_sorry {
            get {
                return ResourceManager.GetString("startup_cfg_sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The URL is empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string startup_cfg_url_error {
            get {
                return ResourceManager.GetString("startup_cfg_url_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When using EpicGamesLauncher に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string startup_cfg_use_epic {
            get {
                return ResourceManager.GetString("startup_cfg_use_epic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open the explanation video in a browser. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string startup_cfg_video_open {
            get {
                return ResourceManager.GetString("startup_cfg_video_open", resourceCulture);
            }
        }
    }
}
