name: MSBuild

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        arch: ["x86", "x64"]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Run MSBuild
        run: msbuild /p:Configuration=Release
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: IVSwitcher_GitHub_actions_artifacts_win-${{matrix.arch}}
          path: IVSwitcher\bin\Release
